### ISSUE TITLE
Loopring Protocol 3.0 Circuit Bug Bounty

### ISSUE THREAD

**Issue by dong77** [Loopring/protocol3-circuits#26]
Loopring has allocated  500,000 LRC for those who identify bugs in Loopring Protocol 3.0's [circuit codebase](https://github.com/Loopring/protocol3-circuits).

## How to compile/test
Please download the [protocol3-circuits](https://github.com/Loopring/protocol3-circuits) and the [protocols](https://github.com/Loopring/protocols) repositories into the same directory, and follow the instructions inside `protocols/packages/loopring_v3/` to compile and test the 3.0 protocol.

Running the whole test suite will likely take several hours.

## Bounty scope
Any confirmed bug will earn the reporter up to **100,000 LRC**.  
Note that duplicate bug reports will NOT be rewarded; optimization suggestions will be rewarded but we do not guarantee the amount of reward.

## How to report a bug?
Please file an issue on github - https://github.com/Loopring/protocol3-circuits/issues

## Bounty expiry
This program expires at the end of November.

**Comment by poma** [comment]
Is Solidity verifier available/included in bounty scope?

**Comment by Brechtpd** [comment]
Hi poma, good seeing you here.

In theory that would have been more for the previous bounty that was specifically for the smart contracts that ended a couple of weeks ago, but because you ask specifically for the solidity verifier I'm guessing you (already) know of a possible issue? :) If so, that would be very important to us of course so I'm sure we will reward you for it if there is indeed a problem with it!
